// Objective-C API for talking to github.com/nknorg/nkn/v2/transaction Go package.
//   gobind -lang=objc github.com/nknorg/nkn/v2/transaction
//
// File is generated by gobind. Do not edit.

#ifndef __Transaction_H__
#define __Transaction_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TransactionTransaction;

@interface TransactionTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Transaction.Transaction with unsupported type: *github.com/nknorg/nkn/v2/pb.Transaction

// skipped method Transaction.Descriptor with unsupported parameter or return types

// skipped method Transaction.DeserializeUnsigned with unsupported parameter or return types

- (NSData* _Nullable)getInfo:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getMessage;
// skipped method Transaction.GetProgramHashes with unsupported parameter or return types

// skipped method Transaction.GetPrograms with unsupported parameter or return types

// skipped method Transaction.GetSize with unsupported parameter or return types

// skipped method Transaction.GetUnsignedTx with unsupported parameter or return types

// skipped method Transaction.Hash with unsupported parameter or return types

- (NSData* _Nullable)marshal:(NSError* _Nullable* _Nullable)error;
- (void)protoMessage;
// skipped method Transaction.ProtoReflect with unsupported parameter or return types

- (void)reset;
// skipped method Transaction.SerializeUnsigned with unsupported parameter or return types

// skipped method Transaction.SetHash with unsupported parameter or return types

// skipped method Transaction.SetPrograms with unsupported parameter or return types

// skipped method Transaction.ShortHash with unsupported parameter or return types

- (NSString* _Nonnull)string;
- (BOOL)unmarshal:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
- (BOOL)verifySignature:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT const int64_t TransactionTransactionNonceLength;

// skipped function HashToShortHash with unsupported parameter or return types


// skipped function NewCoinbase with unsupported parameter or return types


// skipped function NewDeleteName with unsupported parameter or return types


// skipped function NewDeleteNameTransaction with unsupported parameter or return types


// skipped function NewGenerateID with unsupported parameter or return types


// skipped function NewGenerateIDTransaction with unsupported parameter or return types


// skipped function NewIssueAsset with unsupported parameter or return types


// skipped function NewIssueAssetTransaction with unsupported parameter or return types


// skipped function NewMsgTx with unsupported parameter or return types


// skipped function NewNanoPay with unsupported parameter or return types


// skipped function NewNanoPayTransaction with unsupported parameter or return types


// skipped function NewRegisterName with unsupported parameter or return types


// skipped function NewRegisterNameTransaction with unsupported parameter or return types


// skipped function NewSigChainTransaction with unsupported parameter or return types


// skipped function NewSigChainTxn with unsupported parameter or return types


// skipped function NewSubscribe with unsupported parameter or return types


// skipped function NewSubscribeTransaction with unsupported parameter or return types


// skipped function NewTransferAsset with unsupported parameter or return types


// skipped function NewTransferAssetTransaction with unsupported parameter or return types


// skipped function NewTransferName with unsupported parameter or return types


// skipped function NewTransferNameTransaction with unsupported parameter or return types


// skipped function NewUnsubscribe with unsupported parameter or return types


// skipped function NewUnsubscribeTransaction with unsupported parameter or return types


// skipped function Pack with unsupported parameter or return types


// skipped function Unpack with unsupported parameter or return types


#endif
