
// Objective-C API for talking to the following Go packages
//
//	github.com/nknorg/nkn-sdk-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nkn_FRAMEWORK_H__
#define __Nkn_FRAMEWORK_H__

#include "Nkn.objc.h"
#include "Universe.objc.h"

#endif
