
// Objective-C API for talking to the following Go packages
//
//	github.com/nknorg/nkn-sdk-go
//	github.com/nknorg/ncp-go
//	github.com/nknorg/nkn/v2/transaction
//	github.com/nknorg/reedsolomon
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nkn_FRAMEWORK_H__
#define __Nkn_FRAMEWORK_H__

#include "Nkn.objc.h"
#include "Ncp.objc.h"
#include "Transaction.objc.h"
#include "Reedsolomon.objc.h"
#include "Universe.objc.h"

#endif
