// Objective-C API for talking to github.com/nknorg/nkn/transaction Go package.
//   gobind -lang=objc github.com/nknorg/nkn/transaction
//
// File is generated by gobind. Do not edit.

#ifndef __Transaction_H__
#define __Transaction_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TransactionTransaction;
@protocol TransactionIPayload;
@class TransactionIPayload;

@protocol TransactionIPayload <NSObject>
- (NSData* _Nullable)marshal:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshal:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

@interface TransactionTransaction : NSObject <goSeqRefInterface, TransactionIPayload> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Transaction.Transaction with unsupported type: *github.com/nknorg/nkn/pb.Transaction

// skipped method Transaction.Descriptor with unsupported parameter or return types

// skipped method Transaction.DeserializeUnsigned with unsupported parameter or return types

// skipped method Transaction.Equal with unsupported parameter or return types

- (NSData* _Nullable)getInfo:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getMessage;
// skipped method Transaction.GetProgramHashes with unsupported parameter or return types

// skipped method Transaction.GetPrograms with unsupported parameter or return types

// skipped method Transaction.GetSize with unsupported parameter or return types

// skipped method Transaction.GetUnsignedTx with unsupported parameter or return types

- (NSString* _Nonnull)goString;
// skipped method Transaction.Hash with unsupported parameter or return types

- (NSData* _Nullable)marshal:(NSError* _Nullable* _Nullable)error;
- (BOOL)marshalTo:(NSData* _Nullable)dAtA ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)protoMessage;
- (void)reset;
// skipped method Transaction.SerializeUnsigned with unsupported parameter or return types

// skipped method Transaction.SetHash with unsupported parameter or return types

// skipped method Transaction.SetPrograms with unsupported parameter or return types

// skipped method Transaction.ShortHash with unsupported parameter or return types

- (long)size;
- (NSString* _Nonnull)string;
- (NSData* _Nullable)toArray;
- (BOOL)unmarshal:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
- (BOOL)verifySignature:(NSError* _Nullable* _Nullable)error;
- (void)xxX_DiscardUnknown;
- (NSData* _Nullable)xxX_Marshal:(NSData* _Nullable)b deterministic:(BOOL)deterministic error:(NSError* _Nullable* _Nullable)error;
// skipped method Transaction.XXX_Merge with unsupported parameter or return types

- (long)xxX_Size;
- (BOOL)xxX_Unmarshal:(NSData* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT const int64_t TransactionTransactionNonceLength;

// skipped function HashToShortHash with unsupported parameter or return types


// skipped function NewCoinbase with unsupported parameter or return types


FOUNDATION_EXPORT id<TransactionIPayload> _Nullable TransactionNewDeleteName(NSData* _Nullable registrant, NSString* _Nullable name);

// skipped function NewDeleteNameTransaction with unsupported parameter or return types


// skipped function NewGenerateID with unsupported parameter or return types


// skipped function NewGenerateIDTransaction with unsupported parameter or return types


// skipped function NewIssueAsset with unsupported parameter or return types


// skipped function NewIssueAssetTransaction with unsupported parameter or return types


// skipped function NewMsgTx with unsupported parameter or return types


// skipped function NewNanoPay with unsupported parameter or return types


// skipped function NewNanoPayTransaction with unsupported parameter or return types


FOUNDATION_EXPORT id<TransactionIPayload> _Nullable TransactionNewRegisterName(NSData* _Nullable registrant, NSString* _Nullable name, int64_t fee);

// skipped function NewRegisterNameTransaction with unsupported parameter or return types


// skipped function NewSigChainTransaction with unsupported parameter or return types


// skipped function NewSigChainTxn with unsupported parameter or return types


// skipped function NewSubscribe with unsupported parameter or return types


// skipped function NewSubscribeTransaction with unsupported parameter or return types


// skipped function NewTransferAsset with unsupported parameter or return types


// skipped function NewTransferAssetTransaction with unsupported parameter or return types


FOUNDATION_EXPORT id<TransactionIPayload> _Nullable TransactionNewTransferName(NSData* _Nullable registrant, NSData* _Nullable receipt, NSString* _Nullable name);

// skipped function NewTransferNameTransaction with unsupported parameter or return types


FOUNDATION_EXPORT id<TransactionIPayload> _Nullable TransactionNewUnsubscribe(NSData* _Nullable subscriber, NSString* _Nullable id_, NSString* _Nullable topic);

// skipped function NewUnsubscribeTransaction with unsupported parameter or return types


// skipped function Pack with unsupported parameter or return types


// skipped function Unpack with unsupported parameter or return types


@class TransactionIPayload;

@interface TransactionIPayload : NSObject <goSeqRefInterface, TransactionIPayload> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSData* _Nullable)marshal:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshal:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

#endif
